trigger:
  branches:
    include:
      - main

pool:
  name: DeGenAgent
  vmImage: 'windows-latest'

stages:
  - stage: Build_Frontend
    displayName: "Build Frontend"
    jobs:
      - job: Frontend
        displayName: "Install and Build Frontend"
        steps:
          - script: |
              cd client/royaldegen
              npm install
              npm start
            displayName: "Install Dependencies and Build React App"

          - task: CopyFiles@2
            inputs:
              SourceFolder: 'client/royaldegen/build'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/frontend'
            displayName: "Copy Frontend Build Files"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend'
              ArtifactName: 'frontend'
            displayName: "Publish Frontend Build Artifact"

  - stage: Build_Backend
    displayName: "Build Backend"
    jobs:
      - job: Backend
        displayName: "Install Backend and Setup Database"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12.7'
              githubToken: $(gitToken)
            displayName: "Install Python"

          - script: |
              python -m venv venv
              venv\Scripts\activate
              pip install -r server/kingdom1/requirements.txt
            displayName: "Install Dependencies"

          - script: |
              venv\Scripts\activate
              python server/kingdom1/Database.py
            displayName: "Run Database Setup Script"

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'server/kingdom1'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
              replaceExistingArchive: true
            displayName: "Archive Backend Files"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend.zip'
              ArtifactName: 'backend'
            displayName: "Publish Backend Build Artifact"
