trigger:
  branches:
    include:
      - main

pool:
  name: DeGenAgent
  vmImage: 'windows-latest'

stages:
  - stage: Build_Frontend
    displayName: "Build Frontend"
    jobs:
      - job: Frontend
        displayName: "Install and Build Frontend"
        steps:
          - script: |
              cd client/royaldegen
              npm install
              npm start
            displayName: "Install Dependencies and Build React App"

  - stage: Build_Backend
    displayName: "Build Backend"
    jobs:
      - job: Backend
        displayName: "Install Backend and Setup Database"
        steps:
          - script: |
              python -m venv venv
              venv\Scripts\activate
              pip install -r server\kingdom1\requirements.txt
            displayName: "Install Dependencies"

          - script: |
              python server\kingdom1\Database.py
            displayName: "Run Database Setup Script"