version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:80"  # Access the frontend via port 5173

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"  # Access the backend API via port 8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"  # Nginx exposed port
