# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - RoyalDeGeneratorBack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bc1e7843dea94040a2587d3db1d04a7a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a7d80cea0d0a455483fa5c940294e554 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_bc1e7843dea94040a2587d3db1d04a7a }}/oleksandrsokils25416/kingdom-generator_royaldegen/server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'RoyalDeGeneratorBack'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9922943971ad490aaafd1b5be91fa5bb }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_bc1e7843dea94040a2587d3db1d04a7a }}/oleksandrsokils25416/kingdom-generator_royaldegen/server:${{ github.sha }}'